# Generated by Django 5.1.15 on 2026-04-27 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payouts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("from_status", models.CharField(max_length=10)),
                ("to_status", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="payouts.payout",
                    ),
                ),
            ],
            options={
                "db_table": "payout_audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["payout", "created_at"],
                        name="payout_audi_payout__a7f890_idx",
                    )
                ],
            },
        ),
    ]
