# Generated by Django 5.1.15 on 2026-04-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payouts", "0002_payoutauditlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="amount_paise",
            field=models.BigIntegerField(),
        ),
    ]
